#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/mas/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#tint2 & 
fbsetbg -f /home/mas/Pictures/Fc6-wallpaper.png
(sleep 10s && tint2 -c /etc/xdg/tint2/tint2rc) &
(sleep 3s && tint2 -c /usr/local/bin/tint2launchers/tint2rcallbtm) &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/mas/.fluxbox/log"
